In [1]:
import nltk,sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import nltk.data
import csv
from nltk.stem.porter import *
pd.options.mode.chained_assignment = None
from sklearn.preprocessing import LabelEncoder
from numpy import array as arr
from numpy import argmax

In [2]:
arr=[]
file = open("downloaded1.csv",'rt')
samples=csv.reader(file)
c=0
for i in samples:
    c+=1
    
    if c==2:
        x=i[1]
        break

for i in samples:
    if i[1]!=x:
        arr.append(i)


df=pd.DataFrame(data=arr,columns=("types","posts"))
print(len(df.columns))
print(df)

2
         types                                              posts
0     negative  Iranian general says Israel's Iron Dome can't ...
1     positive  with J Davlar 11th. Main rivals are team Polan...
2     negative  Talking about ACT's &amp;&amp; SAT's, deciding...
3     negative  They may have a SuperBowl in Dallas, but Dalla...
4      neutral  Im bringing the monster load of candy tomorrow...
5      neutral  Apple software, retail chiefs out in overhaul:...
6     positive  @oluoch @victor_otti @kunjand I just watched i...
7      neutral  #Livewire Nadal confirmed for Mexican Open in ...
8     positive  @MsSheLahY I didnt want to just pop up... but ...
9      neutral  @Alyoup005 @addicted2haley hmmmm  November is ...
10     neutral  #Iran US delisting MKO from global terrorists ...
11    positive  Good Morning Becky ! Thursday is going to be F...
12     neutral  Expect light-moderate rains over E. Visayas; C...
13    positive  One ticket left for the @49ers game tomorrow! ...
14    ne

In [3]:
def labelencode(df):
    data=df['types']
    values=np.array(data)
    label=LabelEncoder()
    intencode=label.fit_transform(values)
    df['typeint']=intencode
    print(list(label.inverse_transform([0,1,2])))
    #df['typeint'].plot(kind='hist')
    #k=np.arange(0,16)
    #x=label.inverse_transform(k)   #can access encoded actual value using x
    #print(values)
    return df

df=labelencode(df)
#print(df)
shortdata=df.iloc[:,1]
#print(shortdata)

['negative', 'neutral', 'positive']


In [68]:
import string
def preprocess(a):
    from nltk.stem.wordnet import WordNetLemmatizer
    lmtzr = WordNetLemmatizer()
    sentence=a
    from nltk.corpus import stopwords
    ps = PorterStemmer()
    stop=stopwords.words("english")
    
    b=sentence.split()
    for i in sentence.split():
        if i in stop:
            b.remove(i)
    for i in b:
        ps.stem(i)
        lmtzr.lemmatize(i,'v')
    c=""
    for i in b:
        
        c=c+i+" "
   
    clear_string = ""
    for symbol in c:
        if symbol not in string.punctuation:
            clear_string += symbol
    return (strip_all_entities(clear_string))
    
    

preprocess("hello how are you fine chicken.....????  how doing but why!!.")
    
    

'hello fine chicken why'

In [4]:
#removing stopwords 

from nltk.corpus import stopwords
stop=stopwords.words("english")

print('------Removing stopwords------')
shortdata=shortdata.apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
#shortdata=shortdata.apply(lambda x: ' '.join([word for word in x.split() if word!='i' or word!='I']))
print(shortdata)
#stemming of words
ps = PorterStemmer()
print('-------Stemming--------')
shortdata = shortdata.apply(lambda x: ' '.join([ps.stem(word) for word in x.split() ]))
print(shortdata)

------Removing stopwords------
0       Iranian general says Israel's Iron Dome can't ...
1       J Davlar 11th. Main rivals team Poland. Hopefu...
2       Talking ACT's &amp;&amp; SAT's, deciding I wan...
3       They may SuperBowl Dallas, Dallas ain't winnin...
4       Im bringing monster load candy tomorrow, I hop...
5       Apple software, retail chiefs overhaul: SAN FR...
6       @oluoch @victor_otti @kunjand I watched it! Sr...
7       #Livewire Nadal confirmed Mexican Open Februar...
8       @MsSheLahY I didnt want pop up... yep chapel h...
9       @Alyoup005 @addicted2haley hmmmm November odd ...
10      #Iran US delisting MKO global terrorists list ...
11      Good Morning Becky ! Thursday going Fantastic ...
12      Expect light-moderate rains E. Visayas; Cebu, ...
13      One ticket left @49ers game tomorrow! Don't mi...
14      AFC away fans Saturday. All stuff 'she said no...
15      Game 1 NLCS rematch NFC Championship game tomo...
16      Never start working dreams goals 

In [5]:
shortdata=shortdata.apply(lambda x: ' '.join([word for word in x.split() if word.isalpha()]))

from nltk.stem.wordnet import WordNetLemmatizer
lmtzr = WordNetLemmatizer()
#print(shortdata)
print('-------Lemmatization--------')
shortdata = shortdata.apply(lambda x: ' '.join([lmtzr.lemmatize(word,'v') for word in x.split() ]))
print(shortdata)

print('--------Removing punctuations--------')
def clear_punctuation(s):
	import string
	#print("\n")
	clear_string = ""
	for symbol in s:
		if symbol not in string.punctuation:
			clear_string += symbol
	return clear_string

shortdata = shortdata.apply(lambda x: ''.join(clear_punctuation(x))  )
print(shortdata)

-------Lemmatization--------
0       iranian gener say iron dome deal missil talk l...
1       J davlar main rival team hope make success end...
2       talk decid I want go appli colleg everyth coll...
3            they may superbowl dalla win not quarterback
4           Im bring monster load candi I hope get squich
5       appl retail chief san francisco appl inc ceo t...
6                           I watch U rememb sun morn nta
7        nadal confirm mexican open rafael nadal set play
8       I didnt want pop yep chapel hill next wednesda...
9       hmmmm novemb odd releas date true becom big en...
10      US delist mko global terrorist list line iran ...
11                    good morn becki thursday go fantast
12      expect rain samar leyt chanc rain expect fair ...
13      one ticket leave game miss rematch nfc champio...
14              afc away fan all stuff say when turn back
15      game nlc rematch nfc championship game gonna c...
16       never start work dream goal never 

In [6]:
def strip_all_entities(text):
	import string
	entity_prefixes = ['@']
	for separator in  string.punctuation:
		if separator not in entity_prefixes :
			text = text.replace(separator,' ')
	words = []
	for word in text.split():
		word = word.strip()
		if word:
			if word[0] not in entity_prefixes:
				words.append(word)
	return ' '.join(words)

shortdata = shortdata.apply(lambda x: ''.join(strip_all_entities(x))  ) 



In [7]:
i=0
arr=[]
print("-----PREPROCESSED_DATA------")
count=0
for line in shortdata:
    df.iloc[i,1]=line
    i=i+1
print(df)

-----PREPROCESSED_DATA------
         types                                              posts  typeint
0     negative  iranian gener say iron dome deal missil talk l...        0
1     positive  J davlar main rival team hope make success end...        2
2     negative  talk decid I want go appli colleg everyth coll...        0
3     negative       they may superbowl dalla win not quarterback        0
4      neutral      Im bring monster load candi I hope get squich        1
5      neutral  appl retail chief san francisco appl inc ceo t...        1
6     positive                      I watch U rememb sun morn nta        2
7      neutral   nadal confirm mexican open rafael nadal set play        1
8     positive  I didnt want pop yep chapel hill next wednesda...        2
9      neutral  hmmmm novemb odd releas date true becom big en...        1
10     neutral  US delist mko global terrorist list line iran ...        1
11    positive                good morn becki thursday go fantast      

In [8]:
proc_data=np.array(df['posts'])
label=np.array(df['typeint'])
print(len(proc_data))
print(len(label))

6936
6936


In [85]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(proc_data, label,
                                                    stratify=label, 
                                                    test_size=0.1)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))
print(y_test)

6242
694
6242
694
[1 1 2 1 1 0 1 1 1 2 1 2 1 1 0 1 0 1 1 2 0 1 2 1 2 2 2 2 0 0 1 2 2 2 0 2 1
 1 1 1 1 1 1 2 2 0 2 0 1 1 2 1 1 2 0 1 2 2 1 2 1 1 1 2 1 2 1 2 2 2 1 2 1 1
 1 2 1 2 2 2 1 2 0 1 2 2 1 0 1 2 0 2 2 1 2 2 0 2 1 2 0 1 2 1 1 2 0 0 2 1 1
 2 1 2 2 0 2 2 2 1 2 1 0 2 2 1 1 1 1 2 2 1 2 2 1 1 1 0 1 2 2 1 2 2 2 2 2 1
 2 2 2 2 2 1 2 2 2 1 2 2 1 1 1 1 1 2 1 0 2 1 1 2 2 1 2 1 0 2 0 1 1 1 1 2 2
 1 1 1 2 2 0 2 0 1 1 1 2 2 2 2 1 1 1 2 2 0 2 1 1 2 1 1 1 2 0 1 1 1 2 0 1 2
 2 1 1 1 1 1 1 2 1 1 1 1 1 0 2 2 1 0 1 1 1 1 0 0 1 2 0 0 1 1 0 1 2 0 1 1 2
 1 1 2 2 2 1 1 2 2 2 0 1 1 1 1 2 1 2 2 0 2 1 2 1 1 2 1 2 2 2 1 2 0 1 1 0 0
 2 1 1 1 1 1 1 1 1 2 1 1 1 0 1 2 1 1 0 1 0 0 1 2 1 1 1 1 0 1 2 2 1 2 1 1 2
 1 1 2 1 1 2 1 2 1 2 2 1 0 2 0 2 1 1 0 1 1 1 2 1 1 1 1 1 2 1 2 1 0 1 2 1 2
 2 1 1 2 1 1 2 0 0 0 1 2 1 2 1 2 0 0 1 2 1 2 1 1 1 0 1 2 2 0 0 2 2 2 2 1 1
 2 2 2 1 1 1 1 1 2 2 0 2 1 1 2 1 1 2 0 1 2 2 1 2 1 0 2 2 0 1 0 0 2 2 0 1 2
 0 1 2 1 0 1 2 0 0 2 1 1 1 2 1 1 1 2 2 1 1 2 2 1 1 0 1 2 0 1 1 2 2 2 1 1 2
 2 1 1 

In [69]:
stoplist = set('for a of the and to in'.split(' '))
texts = [[word for word in document.lower().split() if word not in stoplist] for document in X_train]
#print(texts)
print(len(X_train))
print(X_train)

6242
['I need nice I want play penni can thi real cougar town make love'
 'mom leave scotland Or keep forget go but place cool I know'
 'dongwoo stash bubblewrap bedroom stop gyu throw coz do pop new' ...
 'spirit hall school color enjoy dress No yoga pant flip you be'
 'ghost spirit vengeanc lose you nowher go and decid dig'
 'tryna make sure everyth go plan']


In [70]:
sentences=[]
for line in X_train:
    sentences.append(line.split())
from gensim.models import Word2Vec
modelw2v=Word2Vec(sentences, size=100, window=5, min_count=1, workers=4)
print(modelw2v)
words=list(modelw2v.wv.vocab)

Word2Vec(vocab=8510, size=100, alpha=0.025)


In [71]:
a=list(modelw2v.wv.vocab.keys())

In [72]:
#optional

import bokeh.plotting as bp
from bokeh.models import HoverTool, BoxSelectTool
from bokeh.plotting import figure, show, output_notebook

# defining the chart
output_notebook()
plot_tfidf = bp.figure(plot_width=700, plot_height=600, title="A map of 10000 word vectors",
    tools="pan,wheel_zoom,box_zoom,reset,hover,previewsave",
    x_axis_type=None, y_axis_type=None, min_border=1)

# getting a list of word vectors. limit to 10000. each is of 200 dimensions
word_vectors = [modelw2v[w] for w in list(modelw2v.wv.vocab.keys())[:5000]]

# dimensionality reduction. converting the vectors to 2d vectors
from sklearn.manifold import TSNE
tsne_model = TSNE(n_components=2, verbose=1, random_state=0)
tsne_w2v = tsne_model.fit_transform(word_vectors)

# putting everything in a dataframe
tsne_df = pd.DataFrame(tsne_w2v, columns=['x', 'y'])
tsne_df['words'] = list(modelw2v.wv.vocab.keys())[:5000]


Loading BokehJS ...

/home/nikitha/.local/lib/python3.6/site-packages/ipykernel_launcher.py:14: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 5000 samples in 0.025s...
[t-SNE] Computed neighbors for 5000 samples in 1.614s...
[t-SNE] Computed conditional probabilities for sample 1000 / 5000
[t-SNE] Computed conditional probabilities for sample 2000 / 5000
[t-SNE] Computed conditional probabilities for sample 3000 / 5000
[t-SNE] Computed conditional probabilities for sample 4000 / 5000
[t-SNE] Computed conditional probabilities for sample 5000 / 5000
[t-SNE] Mean sigma: 0.009215
[t-SNE] KL divergence after 250 iterations with early exaggeration: 70.604027
[t-SNE] KL divergence after 1000 iterations: 1.742267


In [15]:
#optional
# plotting. the corresponding word appears when you hover on the data point.
plot_tfidf.scatter(x='x', y='y', source=tsne_df)
hover = plot_tfidf.select(dict(type=HoverTool))
hover.tooltips={"word": "@words"}
show(plot_tfidf)

In [74]:

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(analyzer=lambda x: x, min_df=10)
matrix = vectorizer.fit_transform([x.split() for x in X_train])
tfidf = dict(zip(vectorizer.get_feature_names(), vectorizer.idf_))
print('vocab size :', len(tfidf))

vocab size : 1094


In [75]:
def buildWordVector(tokens, size):
    vec = np.zeros(size).reshape((1, size))
    count = 0.
    for word in tokens:
        try:
            vec += modelw2v[word].reshape((1, size)) * tfidf[word]
            count += 1.
        except KeyError: # handling the case where the token is not
                         # in the corpus. useful for testing.
            continue
    if count != 0:
        vec /= count
    return vec

In [91]:
a=buildWordVector("hello how are you",100)
print(a)
train_x=[]
for i in X_train:
    train_x.append(buildWordVector(i,100))

/home/nikitha/.local/lib/python3.6/site-packages/ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


[[-1.2732718  -0.11089492 -1.31597647  0.71129942 -0.0112361  -0.62604056
  -0.1828248  -0.14640227 -0.13993186  0.32464769  0.56907277 -0.76645157
  -0.04657844 -0.78187072  0.76813579  0.71665774  0.74511456  1.91000742
  -0.71025705 -0.67093089  0.73820652 -1.37228838  0.56955026 -1.55648306
  -0.43791657 -0.80764845  0.52674353 -0.27210629 -1.270612   -0.55693026
   0.16891304  1.35846853  0.61740741 -0.11472205 -0.14407904 -1.54746035
   0.42700795 -1.59550133 -0.83640413 -0.27406323  0.68320671  0.23962201
   0.4489091   0.5350679  -0.28401325  0.48928206  1.07838316  0.92963472
   0.45636061 -0.40895113 -0.54603836  0.16952975 -0.15534575 -0.13440256
   0.1420265  -0.14335723 -0.56587253 -0.12157708 -0.58138806  0.06464157
  -0.25069273 -0.12078066 -0.76743993 -0.50557584 -0.64530267 -0.4139033
  -0.03518978 -0.01742805  0.57510854  1.64399102 -0.93865485  0.31132324
  -1.20095143 -0.46199912  0.22924282 -0.65283503 -0.21668774 -1.31856772
  -0.07476714  0.29437471  0.53133509 -

In [77]:
import json
import keras
import keras.preprocessing.text as kpt

Using TensorFlow backend.


In [92]:
train_y = keras.utils.to_categorical(y_train, 3)

print(y_train[0])
print(y_train)

1
[1 1 2 ... 1 1 0]


In [136]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation,LSTM

model = Sequential()
model.add(LSTM(32, input_shape=(len(train_x), 100)))
model.add(Dense(500, input_shape=(100,), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))
sgd=keras.optimizers.SGD(lr=0.5, momentum=0.0, decay=0.0, nesterov=False)
model.compile(loss='categorical_crossentropy',
  optimizer=sgd,
  metrics=['accuracy'])

In [145]:
train_x=np.array(train_x)
t=[]
for i in train_x:
       t.append(list(i[0]))
print(t[0])
from numpy import array
t=np.array(t)
t=t.reshape((len(train_x), 100,1))

[-1.1428089141845703, -0.10163720175623894, -1.1705835461616516, 0.6387901306152344, -0.0008056609891355038, -0.5508049666881562, -0.18566062450408935, -0.141170172393322, -0.10718127638101578, 0.2841894835233688, 0.5009398519992828, -0.6786872267723083, -0.04751000627875328, -0.6700366973876953, 0.6996702551841736, 0.6306508362293244, 0.6678769171237946, 1.712457823753357, -0.6523767590522767, -0.5990803301334381, 0.6520018756389618, -1.2214958548545838, 0.5046720266342163, -1.389611041545868, -0.3947512298822403, -0.7179049015045166, 0.4728137791156769, -0.2507136672735214, -1.140161108970642, -0.47631449103355405, 0.14688490480184554, 1.23805832862854, 0.5627812504768371, -0.10524355620145798, -0.140628319978714, -1.4004773497581482, 0.3795748084783554, -1.434299683570862, -0.7447533130645752, -0.24668896645307542, 0.6252391397953033, 0.22340925484895707, 0.39422477781772614, 0.48903279304504393, -0.2439362496137619, 0.43395852446556094, 0.9576228201389313, 0.8137757897377014, 0.423

In [146]:

model.fit(t, train_y,
  batch_size=32,
  epochs=5,
  verbose=1,
  validation_split=0.1,
  shuffle=True)

ValueError: Error when checking input: expected lstm_4_input to have shape (6242, 100) but got array with shape (100, 1)

In [130]:
print(train_y)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
